# Nome do seu workflow
name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # Atualiza a cada 6 horas

jobs:
  generate:
    # Adicione esta seção para dar permissão de escrita ao workflow
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Passo que gera a animação da snake
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # REMOVA a linha "token: ${{ secrets.GITHUB_TOKEN }}" se ela existir aqui
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Passo que faz o commit dos arquivos gerados
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # Ramo onde o arquivo será salvo
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
